### ISSUE TITLE
 parameters.oauth_version: 1.0 gets converted to parameters.oauth_version: 1

### ISSUE THREAD

**Issue by TheMagiche** [jrconlin/oauthsimple#39]
There seems to be a type conversion which causes my request to fail
causes 
Problem: version_rejected | Advice: > oauth_acceptable_versions | 1.0-1.0

**Comment by jrconlin** [comment]
Is this with just one particular language or is it something happening with all the libraries?

**Comment by TheMagiche** [comment]
I don't know, I've only used this library and checked out the source code and everything seems okay. The payment API I'm trying to hook up to was designed to support PHP. Maybe I can send you a link to the source code they implement their OAuth to see. I'm currently stuck on what could be wrong

**Comment by jrconlin** [comment]
Ah, so it's the PHP version. I can look at that. (I think that one was done by someone else, but I remember a fair bit of PHP.)

For what it's worth, you can probably work around this by passing the version as a string rather than as a numeric.

**Comment by TheMagiche** [comment]
Alright, Highly appreciate the help, here's the link https://developer.pesapal.com/documents/OAuth-php.txt . Thanks for helping this noob out.

**Comment by jrconlin** [comment]
Heh, everyone is a noob, we're just at various stages of it for different things

I'm a bit surprised that anything is still using OAuth 1.0 for, well, anything. I figured that OAuth2.0 pretty much dominates the world at this point. 

Looking at what you posted (line 191), it looks like `$version` is being set as a string. 
Later on, (line 522) calling `get_version` returns a float. You probably want that to be a string as well. 

For what it's worth, with a lot of untyped languages (like javascript, python, php, perl, etc.) this is actually a pretty common bug. More than a few of these try to be "helpful" and convert values for you. I'm never a fan of helpful, because it usually isn't. (This is a good case in point.)

Making things even more complicated is that all of this is fed into what OAuth uses as a "Signature String", this is a serialized version of all the parameters, which is then run through a hash and the result is compared as part of the cryptographic signature. Oh, that little voice in the back of your head, the one that it looking confused and raising it's hand politely? Yeah, it's got a point. "Wait, if this is a hash being built out of a string, shouldn't we order the variables?" Yes. yes you should. And you should "normalize" the values as much as possible. 

That's why you should use strings as a baseline here.

Ah, complex systems designed by less than communicative individuals, how could you ever go wrong?

Anyway, the short on this is, you're not crazy, some of this stuff is that complex and weird, and these are the things we should be pointing out better.

Good luck, and try to have some fun.

**Comment by TheMagiche** [comment]
Whoa!... You read my mind. Most of this stuff is still new to me. I'd definitely want to have fun but getting that error kills a little bit of my 'coding soul'. But definitely will keep on trying. If you're ever available to help out I'll appreciate it.

**Comment by jrconlin** [comment]
Heh, best bit of advice I can offer then: Don't get into coding for the joy of programming alone. You'll either write beautiful art that will never be used, or you'll be nibbled to death by dozens of nits and bugs. Find a higher goal that you can use coding to achieve. You'll still have the same level of papercuts, but you'll have a better sense of how you want to invest your time and efforts, so those papercuts will stay just "annoying" rather than soul crushing.

**Comment by TheMagiche** [comment]
And somehow that higher goal shouldn't be money [laughs nervously]. Damn I'd really want to learn as much from you but it would be weird asking way too many questions on an Issue's comment thread. I will definitely seek that higher goal. If I can't find it. I'll ask yours!

**Comment by jrconlin** [comment]
Well, it depends, right? Money is a tool, too. For me, I try to make life for other folks better. It sounds ill-defined because it kind of is. Talking and helping you qualifies to that goal. I earn a good paycheck working for mozilla and try to spend some of that in my community at smaller shops and restaurants. 

I absolutely understand that there's a lot of privilege I benefit from, but I was also raised to make sure others have ladders too. I'm nice to folks because I don't want to live in a world full of a--holes (granted, there are a lot of them, but there are a lot of folks that aren't. They just don't get as much press and attention, sadly.)

You'll probably work for a few not great companies in your hopefully long and successful career, and that's OK. Effect the kind of positive change you can, take their pay, and keep an eye out for the better places when the come. The network of peers and friends you make are FAR more important than the companies you work at (even if the recruiters think otherwise). Peers will have your back because they know you will have theirs. 

Happy to help where I can (although, my PHP skillz are more than 10 years old by now and really rusty).

**Comment by TheMagiche** [comment]
It makes a lot of sense. I wish people had the same perspective on life. Thanks for the great wishes. 
I'm not a PHP dev, I ran away from it a while back when I was learning some programming. I dabble in JavaScript. I had success in building my first npm package thanks to your OAuthsimple lib. Your advice has definitely breathed some life back into me again.
